name: Terraform CD

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Plan terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8 

      - name: Terraform init
        run: terraform init
      
      - name: Terraform plan
        run: terraform plan -var-file=terraform.tfvars

  apply:
    name: Apply terraform
    runs-on: ubuntu-latest
    needs: plan
    environment: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8 

      - name: Terraform init
        run: terraform init
      
      - name: Terraform plan
        run: terraform apply -auto-approve
        